### ISSUE TITLE
Error writing g2s  to netcdf on selected data variables 

### ISSUE THREAD

**Issue by msleckman** [USGS-R/drb_gridmet_tools#1]
Function in [`gridmet.py`](https://github.com/USGS-R/drb_gridmet_tools/blob/main/gridmet.py) extracted the gridmet data for selected variables and run the regridding process from the [grd2shp_xagg package](https://github.com/rmcd-mscb/grd2shp_xagg)

Function inputs for inland salinity are: 
```
polygon_file_path = ' nhru_02.shp',
var_short = ['tmmx', 'tmmn', 'pr', 'srad', 'vs','rmax','rmin','sph'] ,
start_date='1979-01-01', 
end_date='2021-01-01',  # set right now to 1989-01-01 to test script and speed up processing
lat_max = lat_max,  lat_min = lat_min , lon_max = lon_max, lon_min = lon_min
```
Where var_short are defined as: 
```
{'tmmx': 'daily_maximum_temperature',
 'tmmn': 'daily_minimum_temperature',
 'pr': 'precipitation_amount',
 'srad': 'daily_mean_shortwave_radiation_at_surface',
 'vs': 'daily_mean_wind_speed',
 'rmax': 'daily_maximum_relative_humidity',
 'rmin': 'daily_minimum_relative_humidity',
 'sph': 'daily_mean_specific_humidity'}
```
and `lat` `lon` vars are defined by the ~ bbox of the drb

* Comments for review: 
  - [x] Getting Various errors: timeout error when running weights on `grd2shp_xagg` obj, dimension error the last step when writing the g2s object. `g2s.write_gm_file(opath=output_data_folder, prefix= g2s_file_prefix)`
  - [x] For the initializing of grid2shpxagg object (`grd2shp_xagg.Grd2ShpXagg().initialize`), the time_var = 'day'. Do we want to keep our datasets at daily time intervals? 
  - [x] Process takes quite a long time. Any idea how to speed up process?
  - [x] Currently one function for entire regridding. This can be split into 3 different functions if we prefer.

Lmk your thoughts.
 
Issue reviewers: 
Code review: @jsadler2 
Comment review: @jds485

**Comment by rmcd-mscb** [comment]
@msleckman I used your code to debug grd2shp_xagg.  I've fixed the function to output netcdf file.  It was helpful to see you use the code.  You are using it a bit differently than me, which is fine of course, I think the function write_gm_file() is more robust now.  If you bump into more problems just let me know.  I do have a multiprocessing version that splits the process by variable in the branch threadtest but i'll need to merge the changes I made today into that branch - if you really feel the code is too slow we could give that a try :)  Also maybe @jsadler2 mods to xagg will speed things up :)

Also I have not seen any timeout errors myself when generating weights.  I did use it to generate weights for all of GF v1.1  It took a while but completed successfully.

It's a bit challenging to generalize the netcdf output file.  Any suggestions are welcome.

Finally I am beginning to use this code in the operational NHM pipeline so will be working on it and so happy to respond to any issues you are having.

**Comment by jzwart** [comment]
nice work on this @msleckman . Adding some comments based on how temperature forecasting project would use these data. 

>Do we want to keep our datasets at daily time intervals?

I'd assume yes, daily is preferred 

>Currently one function for entire regridding. This can be split into 3 different functions if we prefer.

I'd suggest splitting into 3 different functions which should enable other options to go from grid to point w/o doing the regridding step

**Comment by msleckman** [comment]
@rmcd-mscb Thanks for your help debugging here ! We really appreciate it. I'll let you know if we bump into more problems, and we'll test how to best speed things up, if that is ultimately necessary.

@jzwart  Thanks for your responses to my questions. I'll incorporate that. Still work in progress but we'll make those changes as well as add capability to match to  polylines and points as well.

@jds485 
> Does slice work from max to min? I tested and it returned an empty vector. lat=slice(lat_max, lat_min))

* Believe so. When I run it, the regridded output is within the lat long bounds provided at beginning.

<img width="351" alt="image" src="https://user-images.githubusercontent.com/36547359/150415781-16d89249-9cb6-4c5c-8479-3aa5d0e413bd.png">

> The warning Results from 'centroid' are likely incorrect made me remember your question about if the intersection of the raster and polygon is using the grid or pixel center. Did you find out?
* We touched on this today, but will check closely when I can and confirm

> Is this a Kelvin to Fahrenheit conversion? I've never seen this before. It's probably more intuitive to read a conversion from K to C, then C to F. Also, we can work from K or C for modeling purposes. Slight preference to C. ds_tmax_1["daily_maximum_temperature"] * 9/5 - 459.67
* There was an error, and actually `* 9/5` is not needed and has been removed. I see it as removed in the notebook in this remote repo. Do you? 

> Does your revised function solve this: ValueError: Provide a locale value to localize translation?
* Rebuilding the env. avoids this.

**Comment by rmcd-mscb** [comment]
Hi All, I can help out with regard to the comments above.  

That centroid error is a result of the polygons (nhru_2.shp) using a simple lat/lon projection.  The warning is reported when the center of mass of each polygon in the shapefile is calculated to add a single lat/lon coordinate to each geometry id in the netcdf output file.  I did not re-project the polygons into a more appropriate projection because I use the lat/lons in the output simply, to quickly view the results in an external program (it's an old habit).  We could add the geometry to the netcdf if necessary.  xagg does make a correct re-projection when calculating the area's to determine the intersection weights.  

Also that whacky conversion is simply whacky :) don't know what I was thinking at the time and it was only used for a comparison plot, in other words it's not used in the actual mapping and it's been corrected in the new notebook.

**Comment by jds485** [comment]
> There was an error, and actually * 9/5 is not needed and has been removed. I see it as removed in the notebook in this remote repo. Do you?

It's removed in `grd2shp_drb_IS.ipynb` but not in the folder (probably because it's a checkpoint - can the folder be included in the `.gitignore`?)
